language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - pip install -e .
  - pip install flake8==2.1.0 pep8==1.4.6 pyflakes==0.7.3
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse==1.2.1 unittest2==0.5.1; fi
script:
  - flake8 --statistics *.py
  - python tests.py
  - python setup.py test
matrix:
  allow_failures:
    - python: pypy
